### ISSUE TITLE
High resolution icon asset is invalid

### ISSUE THREAD

**Issue by donatieng** [BlackstoneEngineering/mbed-cli-osx-installer#2]
The other ones seems to be ok, but the highest resolution one is mostly a dark square with a few artefacts at the bottom

**Comment by BlackstoneEngineering** [comment]
Can you please provide a screenshot and the screen resolution on your monitor as well as the version of OSX you are using?

**Comment by donatieng** [comment]
I'm on 2560 x 1600 - you can see the faulty icon if you open the MbedCLI app's package content, then open `Contents/Resources/appIcon.ics` - it's the first one in the list.

**Comment by BlackstoneEngineering** [comment]
yup, i see it now. It looks like im missing a high resolution icon in the initial .icns package im using, which is then getting backfilled with a black image at some point. I'll get this fixed shortly

**Comment by BlackstoneEngineering** [comment]
Fixed here : https://github.com/BlackstoneEngineering/mbed-cli-osx-installer/releases/tag/v0.0.10
